#+TITLE:     Special Directories
#+AUTHOR:    Brian Dewey
#+EMAIL:     bdewey@gmail.com
#+DATE:      2010-01-19 Tue
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 

* Description

Special Directories are a set of directories, each of which has a
function that will navigate you to the appropriate directory using the
push-location cmdlet. For example, the function "home" might navigate
to "c:\users\bdewey."

* Install

Copy the module to somewhere in =ENV:PSModulePath=. Then,

: Install-Module SpecialDirectories

* Using Special Directories

The Get-SpecialDirectories cmdlet will return the list of currently
active special directories. For example:

#+BEGIN_EXAMPLE
C:\users\bdewey\Powershell> Get-SpecialDirectories

Name                           Value
----                           -----
tools                          E:\tools
temp                           C:\Users\bdewey\AppData\Local\Temp
wn                             e:\tools\OneNoteWebAsService
home                           c:\users\bdewey
#+END_EXAMPLE

The Name property is the name of the function that will navigate you
to the directory; the Value property is the directory that you will
navigate to.

- New-SpecialDirectory will create a new special directory.
- Remove-SpecialDirectory will remove a special directory.
- Update-SpecialDirectories will ensure that all of the functions that
  map to special directories are defined.

* History                                              :NOEXPORT:

- 2010-01-19 (1.1.0)

  - Added Invoke-SpecialDirectories.
  - Moved to its own Git repository.
  - Single-sourced documentation into README.org.

- 2009-12-22 (1.0.0)
  
  Initial port to a PowerShell 2.0 module from a loose, baggy
  collection of PowerShell 1.0 scripts.

* License

Microsoft Community License (Ms-CL)
Published: October 12, 2006

   This license governs  use of the  accompanying software. If you use
   the  software, you accept this  license. If you  do  not accept the
   license, do not use the software.

1. Definitions

   The terms "reproduce,"    "reproduction," "derivative works,"   and
   "distribution" have  the same meaning here  as under U.S. copyright
   law.

   A  "contribution" is the  original  software, or  any additions  or
   changes to the software.

   A "contributor"  is any  person  that distributes  its contribution
   under this license.

   "Licensed  patents" are  a contributor's  patent  claims that  read
   directly on its contribution.

2. Grant of Rights

   (A) Copyright   Grant-  Subject to  the   terms  of  this  license,
   including the license conditions and limitations in section 3, each
   contributor grants   you a  non-exclusive,  worldwide, royalty-free
   copyright license to reproduce its contribution, prepare derivative
   works of its  contribution, and distribute  its contribution or any
   derivative works that you create.

   (B) Patent Grant-  Subject to the terms  of this license, including
   the   license   conditions and   limitations   in  section  3, each
   contributor grants you   a non-exclusive, worldwide,   royalty-free
   license under its licensed  patents to make,  have made, use, sell,
   offer   for   sale,  import,  and/or   otherwise   dispose  of  its
   contribution   in  the  software   or   derivative  works  of   the
   contribution in the software.

3. Conditions and Limitations

   (A) Reciprocal  Grants- For any  file you distribute  that contains
   code from the software (in source code  or binary format), you must
   provide recipients the source code  to that file  along with a copy
   of this  license,  which license  will  govern that  file.  You may
   license other  files that are  entirely  your own  work and  do not
   contain code from the software under any terms you choose.

   (B) No Trademark License- This license does not grant you rights to
   use any contributors' name, logo, or trademarks.

   (C)  If you  bring  a patent claim    against any contributor  over
   patents that you claim  are infringed by  the software, your patent
   license from such contributor to the software ends automatically.

   (D) If you distribute any portion of the  software, you must retain
   all copyright, patent, trademark,  and attribution notices that are
   present in the software.

   (E) If  you distribute any  portion of the  software in source code
   form, you may do so only under this license by including a complete
   copy of this license with your  distribution. If you distribute any
   portion  of the software in  compiled or object  code form, you may
   only do so under a license that complies with this license.

   (F) The  software is licensed  "as-is." You bear  the risk of using
   it.  The contributors  give no  express  warranties, guarantees  or
   conditions. You   may have additional  consumer  rights  under your
   local laws   which  this license  cannot   change. To   the  extent
   permitted under  your local  laws,   the contributors  exclude  the
   implied warranties of   merchantability, fitness for  a  particular
   purpose and non-infringement.



